[2024-05-31T09:05:21.457+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.set_up_database scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T09:05:21.465+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.set_up_database scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T09:05:21.466+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T09:05:21.467+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-31T09:05:21.467+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T09:05:21.479+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): set_up_database> on 2024-05-30 00:00:00+00:00
[2024-05-31T09:05:21.483+0000] {standard_task_runner.py:55} INFO - Started process 165 to run task
[2024-05-31T09:05:21.485+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'set_up_database', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmp36lbvj7g']
[2024-05-31T09:05:21.486+0000] {standard_task_runner.py:83} INFO - Job 404: Subtask set_up_database
[2024-05-31T09:05:21.539+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.set_up_database scheduled__2024-05-30T00:00:00+00:00 [running]> on host 731e27f62632
[2024-05-31T09:05:21.595+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=set_up_database
AIRFLOW_CTX_EXECUTION_DATE=2024-05-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-30T00:00:00+00:00
[2024-05-31T09:05:21.596+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-31T09:05:21.597+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/set_up_database.py']
[2024-05-31T09:05:21.606+0000] {subprocess.py:86} INFO - Output:
[2024-05-31T09:05:21.833+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-31T09:05:21.853+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=conference_dag, task_id=set_up_database, execution_date=20240530T000000, start_date=20240531T090521, end_date=20240531T090521
[2024-05-31T09:05:21.899+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-05-31T09:05:21.922+0000] {taskinstance.py:2578} INFO - 3 downstream tasks scheduled from follow-on schedule check
